### PR TITLE
Mrglaydson feature/253 mapeamento tipos processo reativar mapeamento orgao externo

### PR DESCRIPTION
**Pull request by Mauro1706**
Closes: #253

### CODE REVIEW

**Review by sergioadao — CHANGES_REQUESTED** [review]
@mrglaydson ....Após teste da aplicação verificou-se que a aplicação está com os recursos implementados. Segue vídeo da evidência:

issue_253_pr_396_sei4_mysql_21-11-2023 17-52


Porém, o teste funcional:

# make teste=TramiteMapeamentoOrgaoExternoTest test-functional

Apresenta erros, mesmo com as alterações solicitadas no arquivo realizadas no arquivo phpunit.xml :

CONFIGURAÇÕES DE TESTE ÓRGÃO 1:
image

CONFIGURAÇÕES DE TESTE ÓRGÃO 2:
image

linhas 34 e 35
*****    <const name="CONTEXTO_ORGAO_A_UNIDADE_ESTRUTURAS" 
*****      value="CGPRO_SERGIO_ORG1" />

linhas 76 e 77

*****  <const name="CONTEXTO_ORGAO_B_UNIDADE_ESTRUTURAS" 
*****      value="CGPRO_SERGIO_ORG2" />

Segue erro na execução do teste:
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/src/paginas/PaginaTeste.php:35
/tests/src/paginas/PaginaTeste.php:57
/tests/tests/CenarioBaseTestCase.php:231
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:165
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 6, Assertions: 0, Errors: 6.
ERROR: 2
make: *** [Makefile:177: test-functional] Erro 2

**Review by sergioadao — CHANGES_REQUESTED** [review]
@mrglaydson, segue gravação do teste....para complementar as informações já enviadas.

gravacao_teste_253_pr_396_sei4_mysql_22-11-2023 10-42

**Review by sergioadao — CHANGES_REQUESTED** [review]
@Mauro1706  @mrglaydson ......boa tarde....Mauro, conforme solicitado segue resultado do teste funcional.....
Status: Downloaded newer image for selenium/standalone-chrome-debug:latest
Creating funcional_org1-database_1  ... done
Creating funcional_php-test-unit_1  ... done
Creating funcional_org1-memcached_1 ... done
Creating funcional_org2-memcached_1 ... done
Creating funcional_org2-database_1  ... done
Creating funcional_smtp_1           ... done
Creating funcional_org2-http_1      ... done
Creating funcional_org1-http_1      ... done
Creating funcional_proxy_1          ... done
Creating funcional_selenium_1       ... done
Creating funcional_php-test-functional_1 ... done
docker-compose -f tests_sei4/funcional/docker-compose.yml --env-file tests_sei4/funcional/.env run --rm php-test-functional /tests/vendor/bin/phpunit -c /tests/phpunit.xml /tests/tests/TramiteMapeamentoOrgaoExternoTest.php ;
Creating funcional_php-test-functional_run ... done
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHPUnit 8.5.34 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.28 with Xdebug 3.0.4
Configuration: /tests/phpunit.xml

EEEEEE                                                              6 / 6 (100%)

Time: 2.02 minutes, Memory: 8.00 MB

There were 6 errors:

1) TramiteMapeamentoOrgaoExternoTest::test_cadastrar_novo_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:19
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) TramiteMapeamentoOrgaoExternoTest::test_desativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:51
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

3) TramiteMapeamentoOrgaoExternoTest::test_reativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:75
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

4) TramiteMapeamentoOrgaoExternoTest::test_cadastrar_mapeamento_orgao_externo_ja_cadastrado
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:103
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

5) TramiteMapeamentoOrgaoExternoTest::test_editar_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

6) TramiteMapeamentoOrgaoExternoTest::test_excluir_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.15.0-89-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:132
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/tests/CenarioBaseTestCase.php:240
/tests/tests/TramiteMapeamentoOrgaoExternoTest.php:166
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 6, Assertions: 0, Errors: 6.
ERROR: 2
make: *** [Makefile:177: test-functional] Erro 2

**Comment by mrglaydson** [comment]
@sergioadao Por padrão, no teste funcional, ele vai para a tela antes de executar o teste, sempre quando gera um erro na **acao**, ex:  _"selector":"//a[contains(@href, 'acao=pen_map_orgaos_externos_listar')]"}_ significa que a tela não foi encontrada, quando isso ocorre, é erro em permissão no SIP ou modulo está mal configurado.

**Review by sergioadao — CHANGES_REQUESTED** [review]
@glaydson...problemas na aplicação da branch

toor@tesla:~/Documentos/ministerio_economia/sei/aplicacao_sei/sei-4.0.12.15/sei-4-oracle/src/sei/web/modulos/mod-sei-pen$ git pull git@github.com:Mauro1706/mod-sei-pen.git mrglaydson-feature/253-mapeamento-tipos-processo-reativar-mapeamento-orgao-externo
From github.com:Mauro1706/mod-sei-pen
 * branch            mrglaydson-feature/253-mapeamento-tipos-processo-reativar-mapeamento-orgao-externo -> FETCH_HEAD
Mesclagem automática de src/PENIntegracao.php
CONFLITO (conteúdo): conflito de mesclagem em src/PENIntegracao.php
Mesclagem automática de tests_sei3/funcional/tests/CenarioBaseTestCase.php
Mesclagem automática de tests_sei4/funcional/tests/CenarioBaseTestCase.php
Mesclagem automática de tests_super/funcional/tests/CenarioBaseTestCase.php
CONFLITO (conteúdo): conflito de mesclagem em tests_super/funcional/tests/CenarioBaseTestCase.php
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Mauro1706** [comment]
Devido a grande quantidade de commits foi realizado a correção em um outro PR:
https://github.com/pengovbr/mod-sei-pen/pull/401

**Pull request closed without merging**
